#!/usr/bin/env bash


python3 -m pip install PEP517 PIP SetUpTools Wheel --upgrade --break-system-packages

python3 -m pip install -e ".[build, dev, doc, lint, publish, test]" --upgrade --user --break-system-packages
